//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingSystem.API.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingSystem.API.Models.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cannot be performed on this account at this time!.
        /// </summary>
        public static string ERR_INVALID_ACCOUNT_STATE {
            get {
                return ResourceManager.GetString("ERR_INVALID_ACCOUNT_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt. Please try again!.
        /// </summary>
        public static string MSG_LOGIN_INVALID_CRED {
            get {
                return ResourceManager.GetString("MSG_LOGIN_INVALID_CRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been locked.
        /// </summary>
        public static string MSG_LOGIN_LOCKED_ACC {
            get {
                return ResourceManager.GetString("MSG_LOGIN_LOCKED_ACC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login requires email confirmation!.
        /// </summary>
        public static string MSG_LOGIN_REQUIRE_EMAIL_CONFIRM {
            get {
                return ResourceManager.GetString("MSG_LOGIN_REQUIRE_EMAIL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account found with the registered email!.
        /// </summary>
        public static string MSG_RESET_PWD_INVALID_USER {
            get {
                return ResourceManager.GetString("MSG_RESET_PWD_INVALID_USER", resourceCulture);
            }
        }
    }
}
